# Linear queue for the main branch.
queue_rules:
  - name: duplicated main from merge to master
    queue_conditions:
      - label=automerge:merge
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought 
              - check-failure=breakage
              - label=proto:expect-breakage
    merge_conditions:
      - base=master
    merge_method: merge
  - name: duplicated main from rebase updates then merge to master
    queue_conditions:
      - label=automerge:rebase
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought 
              - check-failure=breakage
              - label=proto:expect-breakage
    merge_conditions:
      - base=master
    update_method: rebase
    merge_method: merge
  - name: duplicated main from squash to master
    queue_conditions:
      - label=automerge:squash
      - or:
          - and: # breakage succeeds like we thought
              - check-success=breakage
              - -label=proto:expect-breakage
          - and: # breakage fails like we thought 
              - check-failure=breakage
              - label=proto:expect-breakage
    merge_conditions:
      - base=master
    merge_method: squash

pull_request_rules:
  - name: merge to master + rebase updates then merge to master + squash to master
    conditions: []
    actions:
      queue:
